import {
  GraduationCap, HeartPulse, ShoppingCart, Building2, Landmark, Bot, IndianRupee,
  Users, CalendarCheck, ClipboardList, MessageSquare, Wallet, BarChart3,
  Stethoscope, FileText, Pill, Bell, Receipt, Package, BadgeCheck,
  UserCheck, Banknote, FolderLock, MapPinned, CalendarRange, Handshake,
  Search, FileQuestion, Zap, Settings2, CreditCard, Printer,
} from "lucide-react";

export const PRODUCT_DETAILS = {
  "fee-management": {
    name: "MR AI Fee Management",
    short: "Fee & Transaction Management",
    category: "Flagship Product · Education",
    status: "In Development",
    icon: IndianRupee,
    visual: "dashboard",
    badge: "Demo Data",
    tagline: "Every rupee collected, pending or spent — visible in one calm dashboard.",
    hero: "A practical digital fee and transaction management system designed to simplify educational institution operations. Built for the way Indian schools and colleges actually collect fees — instalments, receipts, concessions and all.",
    features: [
      { icon: Users, title: "Student Management", desc: "Complete student records with class, section and guardian details — searchable in seconds." },
      { icon: Wallet, title: "Fee Structures & Plans", desc: "Define class-wise fee heads, instalments and concessions without touching a spreadsheet." },
      { icon: Receipt, title: "Transactions & Receipts", desc: "Record payments and issue clean digital receipts instantly — no duplicate registers." },
      { icon: CreditCard, title: "Expense Tracking", desc: "Log institutional expenses alongside collections so the real picture is always visible." },
      { icon: BarChart3, title: "Dashboard & Reports", desc: "Daily collections, pending fees and monthly trends presented as decision-ready reports." },
      { icon: FolderLock, title: "Role-Based Access", desc: "Principals, accountants and clerks each see exactly what their role requires." },
    ],
    walkthrough: [
      { num: "01", title: "Set up your institution", desc: "Add classes, students and fee plans in minutes — import from existing records where possible." },
      { num: "02", title: "Collect and record", desc: "Record payments at the counter and hand over a printed or digital receipt on the spot." },
      { num: "03", title: "Track everything live", desc: "Pending fees, today's collections and expenses update on the dashboard as they happen." },
      { num: "04", title: "Report and decide", desc: "Filter, search and export reports for management meetings — no end-of-month scramble." },
    ],
  },
  edutech: {
    name: "MR EduTech",
    short: "School & College Management",
    category: "Product · Education",
    status: "In Development",
    icon: GraduationCap,
    visual: "campus",
    badge: "UI Concept — Demo Data",
    tagline: "Admissions to attendance to announcements — one campus platform.",
    hero: "A modular campus management platform that brings student records, attendance, examinations and parent communication into a single system — designed to work alongside MR AI Fee Management.",
    features: [
      { icon: Users, title: "Admissions & Records", desc: "Structured student profiles from enquiry to enrollment, with documents attached." },
      { icon: CalendarCheck, title: "Attendance", desc: "Class-wise daily attendance with instant summaries for staff and management." },
      { icon: ClipboardList, title: "Exams & Grades", desc: "Exam schedules, marks entry and report cards generated without manual collation." },
      { icon: Wallet, title: "Fee Integration", desc: "Connects natively with MR AI Fee Management for collections and receipts." },
      { icon: MessageSquare, title: "Parent Communication", desc: "Notices, attendance alerts and fee reminders delivered over WhatsApp or SMS." },
      { icon: BadgeCheck, title: "Staff & Roles", desc: "Teachers, office staff and administrators each get a focused, permissioned view." },
    ],
    walkthrough: [
      { num: "01", title: "Digitize the register", desc: "Move admissions and student records out of physical registers into structured profiles." },
      { num: "02", title: "Run the daily routine", desc: "Attendance and timetable updates take minutes, not the first period of the day." },
      { num: "03", title: "Keep parents informed", desc: "Automatic alerts for absences, fees and notices reach parents where they already are." },
      { num: "04", title: "See the whole campus", desc: "Management gets a single view of enrollment, attendance and collection health." },
    ],
  },
  healthtech: {
    name: "MR HealthTech",
    short: "Hospital & Clinic Management",
    category: "Product · Healthcare",
    status: "In Development",
    icon: HeartPulse,
    visual: "clinic",
    badge: "UI Concept — Demo Data",
    tagline: "Shorter queues, cleaner records, calmer clinics.",
    hero: "A clinic and hospital workflow system covering appointments, patient records, OPD billing and pharmacy basics — built for practices that are busy from the moment the doors open.",
    features: [
      { icon: CalendarCheck, title: "Appointments & Queue", desc: "Token-based scheduling that keeps the waiting room moving and patients informed." },
      { icon: Stethoscope, title: "Patient Records", desc: "Visit history, prescriptions and notes organized per patient, retrievable in seconds." },
      { icon: Receipt, title: "OPD Billing", desc: "Consultation, procedure and medicine billing with clean printed invoices." },
      { icon: Pill, title: "Pharmacy Basics", desc: "Track medicine stock and dispense against prescriptions without a separate register." },
      { icon: Bell, title: "Visit Reminders", desc: "Follow-up and appointment reminders over SMS or WhatsApp reduce no-shows." },
      { icon: BarChart3, title: "Practice Reports", desc: "Daily footfall, revenue and pending-payment summaries for the practice owner." },
    ],
    walkthrough: [
      { num: "01", title: "Open the day", desc: "Appointments line up automatically; walk-ins get tokens without confusion at the desk." },
      { num: "02", title: "Consult with context", desc: "The doctor sees history and past prescriptions before the patient sits down." },
      { num: "03", title: "Bill in one flow", desc: "Consultation, medicines and procedures bill together — one invoice, one payment." },
      { num: "04", title: "Close with clarity", desc: "End-of-day summary shows footfall, collections and follow-ups due tomorrow." },
    ],
  },
  commerce: {
    name: "MR Commerce",
    short: "Retail, Billing & Inventory",
    category: "Product · Retail",
    status: "Coming Soon",
    icon: ShoppingCart,
    visual: "pos",
    badge: "UI Concept — Demo Data",
    tagline: "Billing that keeps up with the counter rush.",
    hero: "A point-of-sale and inventory system for retail businesses — fast billing, honest stock counts and sales reports that don't require an accountant to read.",
    features: [
      { icon: Zap, title: "Fast Billing", desc: "A counter-friendly billing screen built for speed during peak hours." },
      { icon: Printer, title: "Invoices & Receipts", desc: "Clean printed and digital invoices with your store's branding." },
      { icon: Package, title: "Stock & Alerts", desc: "Live inventory with low-stock alerts before you discover an empty shelf." },
      { icon: Users, title: "Customer Records", desc: "Purchase history per customer for credit tracking and repeat-business insight." },
      { icon: BarChart3, title: "Sales Reports", desc: "Daily, item-wise and category-wise sales without exporting to Excel first." },
      { icon: BadgeCheck, title: "Counter Roles", desc: "Cashiers bill; only owners edit prices, discounts and stock." },
    ],
    walkthrough: [
      { num: "01", title: "Load your catalog", desc: "Add products with prices and stock — or import your existing item list." },
      { num: "02", title: "Bill at speed", desc: "Search, scan or tap items into a bill; payment closes it and prints the receipt." },
      { num: "03", title: "Stock adjusts itself", desc: "Every sale updates inventory; low items surface before they run out." },
      { num: "04", title: "Know your day", desc: "Closing report shows sales, top items and pending credit at a glance." },
    ],
  },
  office: {
    name: "MR Office",
    short: "HR, Payroll & Attendance",
    category: "Product · Workplace",
    status: "Coming Soon",
    icon: Building2,
    visual: "hr",
    badge: "UI Concept — Demo Data",
    tagline: "Payroll day without the spreadsheet marathon.",
    hero: "An HR and payroll system for growing offices — employee records, attendance, leave and salary processing in one place, built for Indian small-business reality.",
    features: [
      { icon: Users, title: "Employee Records", desc: "Profiles, documents and joining details organized per employee." },
      { icon: UserCheck, title: "Attendance & Leave", desc: "Daily attendance with leave applications and approvals in one flow." },
      { icon: Banknote, title: "Payroll Processing", desc: "Salary structures, deductions and payslips generated from attendance automatically." },
      { icon: FolderLock, title: "Document Locker", desc: "Offer letters, IDs and contracts stored against each employee, access-controlled." },
      { icon: Bell, title: "Reminders", desc: "Probation endings, document expiries and payroll deadlines surface on time." },
      { icon: BarChart3, title: "HR Reports", desc: "Headcount, attendance trends and payroll cost summaries for management." },
    ],
    walkthrough: [
      { num: "01", title: "Add your team", desc: "Create employee profiles with salary structures and documents in one sitting." },
      { num: "02", title: "Track the month", desc: "Attendance and leave flow in daily; nothing to reconstruct at month-end." },
      { num: "03", title: "Run payroll", desc: "Salaries compute from attendance with deductions applied — review, approve, done." },
      { num: "04", title: "Share payslips", desc: "Employees receive payslips digitally; records stay audit-ready." },
    ],
  },
  property: {
    name: "MR Property",
    short: "Real Estate & Property Management",
    category: "Product · Real Estate",
    status: "Coming Soon",
    icon: Landmark,
    visual: "property",
    badge: "UI Concept — Demo Data",
    tagline: "Every plot, booking and instalment — mapped and tracked.",
    hero: "A project and property management system for real estate teams — plot registries, customer bookings, payment schedules and site-visit tracking built for how property actually sells.",
    features: [
      { icon: MapPinned, title: "Plot Registry", desc: "A visual map of every plot — available, booked or sold — always current." },
      { icon: Handshake, title: "Bookings & Customers", desc: "Booking records with customer details, agreements and payment terms attached." },
      { icon: CalendarRange, title: "Payment Schedules", desc: "Instalment plans per booking with due-date tracking and receipts." },
      { icon: Bell, title: "Instalment Reminders", desc: "Due and overdue instalment reminders reach customers over WhatsApp or SMS." },
      { icon: Users, title: "Team & Broker Roles", desc: "Sales staff and brokers see their deals; owners see everything." },
      { icon: BarChart3, title: "Sales Reports", desc: "Inventory sold, collections received and expected cash flow per project." },
    ],
    walkthrough: [
      { num: "01", title: "Map the project", desc: "Lay out plots and pricing once; the registry stays live as bookings happen." },
      { num: "02", title: "Book with a schedule", desc: "Each booking gets its instalment plan — no separate diary per customer." },
      { num: "03", title: "Collect on time", desc: "Reminders go out before due dates; receipts record every payment." },
      { num: "04", title: "See the project clearly", desc: "Sold versus available, collected versus expected — one dashboard per project." },
    ],
  },
  "ai-assistant": {
    name: "MR AI Assistant",
    short: "AI-Powered Business Assistance",
    category: "Product · Artificial Intelligence",
    status: "In Development",
    icon: Bot,
    visual: "assistant",
    badge: "UI Concept — Simulated",
    tagline: "Ask your business a question. Get an answer, not a spreadsheet.",
    hero: "A context-aware AI assistant that sits on top of your business data — answering questions, drafting summaries and triggering routine workflows in plain language, including over WhatsApp.",
    features: [
      { icon: Search, title: "Natural-Language Queries", desc: "Ask 'how much is pending this month?' and get a direct answer from your data." },
      { icon: FileText, title: "Business Summaries", desc: "Daily, weekly or monthly summaries drafted automatically in plain language." },
      { icon: FileQuestion, title: "Document Q&A", desc: "Ask questions across uploaded documents, receipts and records." },
      { icon: Zap, title: "Workflow Triggers", desc: "'Remind everyone with pending fees' becomes an actual scheduled action." },
      { icon: MessageSquare, title: "WhatsApp Interface", desc: "Owners query and command the assistant from the app they already live in." },
      { icon: Settings2, title: "Admin Controls", desc: "You decide what data the assistant can see and what actions it may take." },
    ],
    walkthrough: [
      { num: "01", title: "Connect your data", desc: "Link the assistant to your MR AI products or existing records with permissioned access." },
      { num: "02", title: "Ask in plain words", desc: "Questions in everyday language return answers grounded in your actual numbers." },
      { num: "03", title: "Automate the routine", desc: "Recurring summaries, reminders and reports run on schedule without being asked twice." },
      { num: "04", title: "Stay in control", desc: "Every action is logged; sensitive operations always wait for your approval." },
    ],
  },
};
